name: XAPK AzurLane JMBQ Build Work

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select Game Server'
        required: true
        type: choice
        options:
          - 'TW'
          - 'EN'
          - 'JP'
          - 'KR'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "18"
          distribution: "adopt"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;35.0.0"
      
      - name: Build APK
        run: |
          chmod +x merge_build.sh
          ./merge_build.sh "${{ github.event.inputs.region }}"

      - name: Generate Release Notes
        run: |
          cp RELEASE_NOTES.md current_release.md
          
          echo "" >> current_release.md
          echo "### 📦 Build Details" >> current_release.md
      
      - name: Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.JMBQ_VERSION }}-XAPK"
          name: "AzurLane JMBQ ${{ env.JMBQ_VERSION }} Build XAPK"
          artifacts: "${{ github.event.inputs.region }}-V.${{ env.VERSION }}.7z.*"
          allowUpdates: true
          bodyFile: "current_release.md"
